### ISSUE TITLE
Tethys App Store Name

### ISSUE THREAD

**Issue by swainn** [BYU-Hydroinformatics/tethysapp-tethys_app_store#12]
I noticed that the repository has been renamed "app_store". I have a few suggestions:

* Call it the Tethys App Store
* Use the Tethys app naming convention
* For example: tethysapp-tethys_app_store

Also, renaming the repo doesn't actually rename the app. I recommend doing the following:

* Minimum: Change name of app to "App Store" in app.py
* Better: Change the app package and URL root for the app to "app_store" and "app-store"

**Comment by swainn** [comment]
Thought of a few other things related to renaming:
* Documentation and README need to be updated
* Conda and/or pip packages need to be made with new name

**Comment by danames** [comment]
Agree with all. Rohit has been working to rename everything so this is good
input.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rileyhales** [comment]
> * Better: Change the app package and URL root for the app to "app_store" and "app-store"

I agree with this but we need to double check this url changes won't break any of the github actions workflows we built. Or at least sync updating both.

**Comment by rileyhales** [comment]
Have we thought about the ramifications of the name changes to the draft of a paper in the EMS peer review phase? I think we should definitely try to get the paper to reflect the name change or i would become unsure if its wise to rename.

Next time we have a chance to do edits we can edit it and make a note that we reconsidered the propose warehouse name for various reasons.

**Comment by danames** [comment]
Rohit is working on revisions to the EMS paper at the same time, so we're
going to push through the name change in both places...
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rfun** [comment]
Thanks for all the suggestions @swainn. The new version has been pushed out and the app has been renamed accordingly. Please let me know if you see any issues. Closing this issue for now.
