### ISSUE TITLE
Documentation Links Don't Work

### ISSUE THREAD

**Issue by swainn** [BYU-Hydroinformatics/tethysapp-tethys_app_store#13]
The Read the Docs links don't work:

https://tethys-app-warehouse.readthedocs.io/en/latest

![image](https://user-images.githubusercontent.com/5123221/129941028-54d62165-652d-4b28-b41a-faf07fe3a719.png)

**Comment by danames** [comment]
Where is it linked from?
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rfun** [comment]
This comes from the GitHub Repo. I have a new URL setup : https://app-store.readthedocs.io/en/latest/ but all my rename changes are in a different branch right now. Also based on the suggestion in a different issue, I am going to update the docs url again to tethys-app-store.readthedocs.io. Will call this resolved once I push those changes out.

**Comment by danames** [comment]
Sounds good. Thanks.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rfun** [comment]
This has been resolved now: https://tethys-app-store.readthedocs.io/en/latest/
